---
services:

  gateway:
    build:
      context: .
      dockerfile: docker/apigateway/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - heicrm
    depends_on:
      - auth
      - users

  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    networks:
      - heicrm
    depends_on:
      - db
      - redis
      - nats

  users:
    build:
      context: .
      dockerfile: docker/users/Dockerfile
    networks:
      - heicrm
    depends_on:
      - db
      - nats
      - redis

  housing:
    build:
      context: .
      dockerfile: docker/housing/Dockerfile
    networks:
      - heicrm
    depends_on:
      - db
      - nats
      - redis

  tasks:
    build:
      context: .
      dockerfile: docker/tasks/Dockerfile
    networks:
      - heicrm
    depends_on:
      - db
      - nats
      - redis

  notify:
    build:
      context: .
      dockerfile: docker/notify/Dockerfile
    networks:
      - heicrm
    depends_on:
      - db
      - nats
      - redis

  db:
    image: postgres:18
    container_name: database
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - heicrm
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  nats:
    image: nats:2
    container_name: nats
    command: [ "-js","-m","8222","-p","4222","-sd","/data" ]
    ports: [ "4222:4222","8222:8222" ]
    volumes: [ "./nats:/data" ]
    networks:
      - heicrm
  redis:
    image: redis:alpine3.22
    container_name: redis_cache
    restart: unless-stopped
    networks:
      - heicrm
    ports:
      - "6379:6379"

volumes:
  pgdata:

networks:
  heicrm: